# Generated by Django 6.1 on 2026-09-05 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('borrowing', '0002_borrowingmodel_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='borrowingmodel',
            name='image',
        ),
    ]
