# Generated by Django 6.0.6 on 2026-08-25 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookmodel',
            name='stock',
            field=models.IntegerField(default=5),
        ),
    ]
